language: minimal
sudo: required
services:
  - docker
env:
  global:
    secure: QyCK51F2OVY7Xcn3zMH9Pbfm6NDYayJF5A2Onf7iG8xTMjTVJys/qjaubH0c3ZrIEG7HQfKvxP5HPEzuKUgB6yaQn0Z6NuSlXqQLbkN7KT6AcieyPB9JR/p5lU+tB4SZLAdWztsriL+rOQ83ms0u805e3K/ty2EmM+yL5flLIsfmzp2lcXUKkwLyOXo7AMgfP+iwR2tIykxmZP3SGZD9dumF9rH7vZDr65EtGqBfU0FuLyvNxY1UgShEPynXaaAs/E0nbTajLiFQw/vZ+xAlk4AcEWagjW3xQE3cspahfRt/S8w/6zcXpoiyLUu7lkMrT60HxZ/2xe+uZ98niA1toyFaA2wdWwAO3iEURgsoER04sSg6NoL/wxUzYSVvqPjcfdhul5jcCsgJaFQyU55BvovMUVDFt09q6wyENanBwzlHU5QiR8XDq4whoqpO7FFI8dm43QxqjDEKj7KpIXHfd9DQ7mWQnXnyRxXcG2bSnIQ/WOSWDHK4n9lzmAmgN6mGHodZI4bwz5IlLZLfmUgYTBjdk+SzJYHM9WVT6FTb5PuURmMliuzx/vKrXKzYQd5/rB+8zgnim9l4WIxrI21f1uA5Q8JqjV1jsCQUDHSVRCV+5md7MS5l/foDXYkbr1uRNWvC4wES6QeyDC+kJnn+xLUGIlqo9D93L5LyNkEf9R4=
script: make
deploy:
  provider: script
  script: make publish
  on:
    branch: master
    tags: true